config/routes.rb
Conference::Application.routes.draw do

  scope "/(:locale)" do
    root :to => 'static#main'
    match 'page/:action', :controller => :static

    resources :users do
      resource :report, :only => [:edit, :update] do
        member do
          get :delete_time
        end
      end

      collection do
        get :program
      end
    end

    resource :user_sessions, :only => [:new, :create, :destroy]
    match :upload, :to => "data_file#upload", :method => :post
    match :delete_all, :to => "data_file#delete_all", :method => :delete
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :full_address, :email

  validates_format_of :email,
                      :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i,
                      :message => 'email must be valid'

  #validates_format_of :home_phone, :with => /^[0-9]{10}$/,
  #                    :if => Proc.new { |o| !o.home_phone.blank? }
  #validates_format_of :work_phone, :with => /^[0-9]{10}$/,
  #                    :if => Proc.new { |o| !o.work_phone.blank? }


  before_validation :delete_symbols_from_phone

  private

  def delete_symbols_from_phone
    [work_phone].each { |p| p.gsub!(/\D+/, '') }
  end
end

app/models/data_file.rb
class DataFile

  def self.save(upload, dirname)
    spl = upload.original_filename.split('.')
    ext = spl[spl.length-1]
    name =  File.basename(upload.original_filename).gsub(/.#{ext}/,'')<<'.'<<ext
    path = File.join("public/#{dirname}", name)
    File.open(path, "wb") { |f| f.write(upload.read) }
    return name
  end

  def self.delete_all_pdf(dirname)
    files = Dir.glob("public/#{dirname}/*.pdf")
    files.each{|f| File.delete(f)}
  end

  def self.get_first_pdf(dirname)
    Dir.glob("public/#{dirname}/*.pdf").first
  end

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :topic

  SECTION = ['Approximation Theory', 'Fourier Analysis', 'Mapping Theory']
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :report
  has_one :address

  accepts_nested_attributes_for :report
  accepts_nested_attributes_for :address
  
  validates_associated :report, :address
  validates_presence_of :first_name, :last_name, :place_of_work, :position

  delegate :section, :to => :report

  def self.for_program
    self.includes(:report).where('reports.begin_report is not null and reports.end_report is not null').
                  order('reports.begin_report').group_by(&:section).
                  map{|k,v| {k => v.group_by(&:date_for_group)}}.inject({}){|sum,x|sum.merge(x)}
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def date_for_group
    report.begin_report.beginning_of_day.strftime('%d-%m-%Y') if report.begin_report
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :authenticated?
  before_filter :set_locale
  before_filter :find_abstract

  def require_admin
    redirect_to root_url unless authenticated?
  end

  def authenticated?
    session[:admin] == 'admin'
  end

  def set_locale
    # ((lang = request.env['HTTP_ACCEPT_LANGUAGE']) && lang[/^[a-z]{2}/])
     I18n.locale = ['en', 'ru', 'uk'].include?(params[:locale]) ? params[:locale] :  'en'
  end

  def default_url_options(options = {})
    {:locale => I18n.locale}
  end

  def find_abstract
    @pdf = DataFile.get_first_pdf('abstract').gsub('public', '')  unless  DataFile.get_first_pdf('abstract').blank?
  end
end

app/controllers/data_file_controller.rb
class DataFileController < ApplicationController
  before_filter :require_admin

  def upload
    begin
      DataFile.save(params[:upload], params[:dirname])
    rescue
      flash[:error] = 'Upload error'
    end
    redirect_to :back
  end

  def delete_all
    DataFile.delete_all_pdf(params[:dirname])
    redirect_to :back
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :set_user

  def edit
  end

  def update
    if @user.report.update_attributes(params[:report])
      flash[:notice] = t 'flash.update_report'
    end
    redirect_to program_users_path
  end

  def delete_time
    report = @user.report
    report.begin_report = nil
    report.end_report = nil
    report.save
    redirect_to program_users_path
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
  end

  def create
   if Digest::SHA1.hexdigest(params[:admin]+PAS_SALT) == CRYPTED_PAS
      session[:admin] = 'admin'
    end
    redirect_to root_url
  end

  def destroy
    session[:admin] =  nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin, :except => [:index, :program]
  before_filter :get_user, :only => [:show, :edit, :update, :destroy]

  def index
    @users = User.find(:all, :include => [:report]).group_by(&:section)
  end

  def show
  end

  def new
    @user = User.new
    @user.build_address
    @user.build_report
  end

  def create
    @user = User.new params[:user]
    if @user.save
      flash[:notice] = t 'flash.add_user'
      redirect_to users_path
    else
      flash[:error] = t 'flash.bad_add_user'
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = t 'flash.update_user'
      redirect_to user_path(@user)
    else
      flash[:error] = t 'flash.bad_update_user'
      render :action => :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def program
    @users = User.for_program
    @pdf_rasp = DataFile.get_first_pdf('rasp').gsub('public', '')  unless  DataFile.get_first_pdf('rasp').blank?
  end

  private

  def get_user
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def lang_menu(this_page)

    if root_url.match(this_page)
      this_page = root_url
    end

    ['uk', 'en', 'ru'].each do |lang|
      this_page.gsub!(/\/[a-z]{2}(\/|$)/, "/#{lang}/")
      concat content_tag :span, link_to(lang, "#{this_page}")
    end
  end

  def login_url
    if authenticated?
      concat link_to(t('auth.logout'), user_sessions_path, :method => :delete)
    else
      concat link_to(t('auth.login'), new_user_sessions_path, :remote => true)
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t ("titles.#{controller.controller_name}.#{controller.action_name}") %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js", "jquery.rails.js" %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id='wrapper'>
  <div id='header'>
    <div id='title'>
      <p>
        <%= t('header.donnu')%>
      </p>

      <p id="name">
        <%= t('header.conference_name')%>
      </p>

      <p>
        <%= t('header.conference_data')%>
      </p>

    </div>
    <div id='lang'>
      <% lang_menu(request.env['REQUEST_URI']) %>
      <span id='login_place'>
      <% login_url %>
    </span>
    </div>
  </div>


  <div id='menu'>
    <ul>
      <li> <%= link_to(t("menu.main"), root_url) %></li>
      <li> <%= link_to(t("menu.registration"), {:controller => :users, :action => :new}) %></li>
      <li> <%= link_to(t("menu.list"), {:controller => :users, :action => :index}) %></li>
      <li> <%= link_to(t("menu.program"), program_users_path) %></li>
      <li> <%= link_to(t("menu.contacts"), {:controller => :static, :action => :contacts}) %></li>
      <li> <%= link_to(t('abstract'), @pdf) if @pdf %> </li>
    </ul>
  </div>

  <div id='content'>
    <%= yield %>
  </div>
</div>

<div id='footer'>
  <div id='donnu_link'>
    <a href="http://www.donnu.edu.ua/">Donetsk National University</a>
  </div>
</div>

</body>
</html>

app/views/reports/edit.js.erb
$('#<%="form_#{@user.id}"%>').toggle()

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path do %>
    <%= password_field_tag :admin %>
    <%= submit_tag 'Log in', :class => "button" %>
<% end %>

app/views/user_sessions/new.html.erb
<% form_tag user_sessions_path do %>
<%= text_field_tag :admin %>
<%= submit_tag %>
<% end %>

app/views/user_sessions/new.js.erb
$('#login_place').html('<%= escape_javascript(render(:partial => 'form')) %>');

app/views/users/_form.html.erb
<h3><%= flash[:error] %></h3>

<%= form_for @user do |f| %>
    <%= f.error_messages %>
    <div>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div>
      <%= f.label :birthday %>
      <%= f.date_select :birthday, :start_year => 1920, :end_year => 2000 %>
    </div>
    <div>
      <%= f.label :place_of_work %>
      <%= f.text_area :place_of_work %>
    </div>
    <div>
      <%= f.label :position %>
      <%= f.text_field :position %>
    </div>
    <%= f.fields_for :report do |r| %>

        <div>
          <%= r.label :topic %>
          <%= r.text_field :topic, :class => 'report_thema' %>
        </div>
        <div>
          <%= r.label :section %>
          <%= r.select :section, Report::SECTION %>
        </div>
    <% end %>

    <%= f.fields_for :address do |a| %>
        <div>
          <%= a.label :full_address %>
          <%= a.text_area :full_address %>
        </div>
        <div>
          <%= a.label :email %>
          <%= a.text_field :email %>
        </div>
        <div>
          <%= a.label :work_phone %>
          <%= a.text_field :work_phone %>
        </div>

        <h4><%= t('invitation')%>:</h4>
        <br />
        <div>
          <%= a.label :email_invitation %>
          <%= a.check_box :email_invitation %>
        </div>
        <div>
          <%= a.label :post_invitation %>
          <%= a.check_box :post_invitation %>
        </div>
    <% end %>

    <%= f.submit t('create'), :class => 'button' %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<% if authenticated? %>
    <%= form_tag upload_path, :multipart => true do %>
        <%= file_field_tag :upload %><br />
        <%= hidden_field_tag :dirname, 'abstract' %><br />
        <%= submit_tag 'Upload', :class => 'button' %>
    <% end %>
    <%= link_to('Delete last version of abstracts', delete_all_path(:dirname => 'abstract'), :method => :delete) if @pdf %>
<% end %>

<h3><%= User.model_name.human(:count => @users.count) %></h3>
<br/>
<%= link_to(t('abstract'), @pdf) if @pdf %>
<br/>
<br/>

<% @users.each_key do |key| %>
    <h4><%= key %></h4>
    <table>
      <% @users[key].each do |user| %>
          <tr class='user_info'>
            <td class='name'><%= user.full_name %></td>
            <td class='work'><%= user.place_of_work %></td>
            <td class='topic'><%= user.report.topic %></td>
          </tr>

          <% if authenticated? %>
              <tr>
                <td><%= link_to t('link.admin.show'), user %></td>
                <td><%= link_to t('link.admin.edit_time'), edit_user_report_path(user), :remote => true %></td>
                <td><%= link_to t('link.admin.delete'), user, :confirm => "confirmation", :method => :delete %></td>
              </tr>
          <% end %>

          <% if authenticated? %>
              <tr style="display:none" id=<%= "form_#{user.id}" %>>
                <td colspan=3>
                  <% form_for user.report, :url => user_report_path(user) do |f| %>
                      <%= f.error_messages %>
                      <%= f.datetime_select :begin_report, :discard_year => true %>
                      <%= f.datetime_select :end_report, :discard_year => true %>
                      <%= f.submit 'Update' %>
                  <% end %>
                </td>
              </tr>
          <% end %>
      <% end %>
    </table>
<% end %>

app/views/users/new.html.erb
<span class="subtitle"> <%= t('subtitle.reg')%></span>
<%= render 'form' %>
<%= t 'questions' %> <%= mail_to "conf_ma2011@mail.ru" %>.

app/views/users/program.html.erb
<% if authenticated? %>
    <%= form_tag upload_path, :multipart => true do %>
        <%= file_field_tag :upload %><br />
        <%= hidden_field_tag :dirname, 'rasp' %><br />
        <%= submit_tag 'Upload', :class => 'button' %>
    <% end %>
    <%= link_to('Delete', delete_all_path(:dirname => 'rasp'), :method => :delete) if @pdf_rasp %>
<% end %>

<h3><%= t('shedule') %></h3>
<br/>
<%= link_to(t('rasp'), @pdf_rasp) if @pdf_rasp %>
<br/>
<br/>

<% @users.each do |section, hash| %>
    <h3><%= section %></h3>
    <br/>
    <% hash.each_key do |date| %>
        <h5><%= date.inspect %></h5>
        <table>
          <% hash[date].each do |user| %>
              <tr class='user_info'>
                <td class='name2'><%= user.full_name %></td>
                <td class='work2'><%= user.place_of_work %></td>
                <td class='topic2'><%= user.report.topic %></td>
                <td class='time2'><%= "#{user.report.begin_report.strftime('%H:%M')} - #{user.report.end_report.strftime('%H:%M')}" %></td>
              </tr>
              <% if authenticated? %>
                  <tr>
                    <td class='link'><%= link_to t('link.admin.show'), user %></td>
                    <td class='link'><%= link_to t('link.admin.edit_time'), edit_user_report_path(user), :remote => true %></td>
                    <td class='link'><%= link_to t('link.admin.delete_time'), delete_time_user_report_path(user) %></td>
                    <td class='link'><%= link_to t('link.admin.delete'), user, :confirm => "confirmation", :method => :delete %></td>
                  </tr>
                  <tr style="display:none" id=<%= "form_#{user.id}" %>>
                    <td colspan=4>
                      <% form_for user.report, :url => user_report_path(user) do |f| %>
                          <%= f.error_messages %>
                          <%= f.datetime_select :begin_report, :discard_year => true %>
                          <%= f.datetime_select :end_report, :discard_year => true %>
                          <%= f.submit 'Update' %>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
          <% end %>
        </table>
    <% end %>

<% end %>

app/views/users/show.html.erb
<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Birthday:</b>
  <%= @user.birthday %>
</p>

<p>
  <b>Place of work:</b>
  <%= @user.place_of_work %>
</p>

<p>
  <b>Position:</b>
  <%= @user.position %>
</p>

<p>
  <b>Topic:</b>
  <%= @user.report.topic %>
</p>

<p>
  <b>Section:</b>
  <%= @user.report.section %>
</p>

<p>
  <b>Begin report:</b>
  <%= @user.report.begin_report %>
</p>

<p>
  <b>End report:</b>
  <%= @user.report.end_report %>
</p>

<p>
  <b>Address:</b>
  <%= @user.address.full_address %>
</p>

<p>
  <b>Work phone:</b>
  <%= @user.address.work_phone %>
</p>

<p>
  <b>Email:</b>
  <%= @user.address.email %>
</p>

<p>
  <b>Email invitation:</b>
  <%= @user.address.email_invitation %>
</p>

<p>
  <b>Postal invitation:</b>
  <%= @user.address.post_invitation %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %>